local   all             all                                     reject
host    all             all             127.0.0.1/32            reject
host    all             all             ::1/128                 reject
hostnossl all           all             0.0.0.0/0               reject
hostnossl all           all             ::0/0                   reject
hostssl all             all             0.0.0.0/0               cert clientcert=verify-full
hostssl all             all             ::0/0                   cert clientcert=verify-full
