name: atm-sim

volumes:
  postgres:

networks:
  internal:
    driver: bridge

x-database-url: &database-url
  DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}

services:
  postgres:
    image: postgres:17
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - internal

  migrations:
    build:
      dockerfile: backend/Dockerfile.migrations
      context: .
    environment:
      <<: *database-url
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - internal

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    environment:
      <<: *database-url
      BACKEND_ADDRESS: "${BACKEND_ADDRESS}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    restart: "unless-stopped"
