FROM rust:latest

WORKDIR /app

RUN cargo install diesel_cli --no-default-features --features postgres

COPY backend/diesel.toml ./diesel.toml
COPY backend/migrations ./migrations

CMD ["diesel", "migration", "run"]
